config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root to: "home#index"
  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :twitter_accounts
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do 
	self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do
	if publish_at_previously_changed?
		TweetJob.perform_at(self.publish_at, self.id)
	end
  end

  def published?
	tweet_id?
  end

  def publish_to_twitter!
	tweet = twitter_account.client.update(body)
	update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
	validates :username, uniqueness: true
      	belongs_to :user
	has_many :tweets, dependent: :destroy

	def client
	  Twitter::REST::Client.new do |config|
	    config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)

	    config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)

	    config.access_token        = token
	    config.access_token_secret = secret
	  end
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets
      	# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
        before_action :authenticate_user!
	def twitter
		twitter_account = current_user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
		twitter_account.update(
			name: auth.info.name,
			username: auth.info.nickname,
			image: auth.info.image,
			token: auth.credentials.token,
			secret: auth.credentials.secret,
		)
		redirect_to root_path, notice: "Successfully connected your account"
	end

	def auth
		request.env['omniauth.auth']
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_tweet, only: [:edit, :update, :destroy]

	def index
		@tweets = current_user.tweets
	end

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = current_user.tweets.new(tweet_params)
		if @tweet.save
			redirect_to tweets_path, notice: "Tweet was scheduled successfully"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @tweet.update(tweet_params)
			redirect_to tweets_path, notice: "Tweet was updated successfully"
		else
			render :edit
		end
	end

	def destroy
		@tweet.destroy
		redirect_to tweets_path, notice: "Tweet was unscheduled"
	end

	private
	def tweet_params
		params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
	end

	def set_tweet
		@tweet = current_user.tweets.find(params[:id])
	end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_twitter_account, only: [:destroy]
	def index
		@twitter_accounts = current_user.twitter_accounts
	end

	def destroy
		@twitter_account = current_user.twitter_accounts.find(params[:id])
		@twitter_account.destroy
		redirect_to twitter_accounts_path, notice: "Successfully disconnected @#{@twitter_account.username}"
	end

	private
	def set_twitter_account
		@twitter_account = current_user.twitter_accounts.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to Shawn's Twitter Tool</h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Twitter Tool', root_path,class:"navbar-brand"%>
	
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      <% if user_signed_in? %>
      <li class="nav-item">
	   <%= link_to "Twitter Accounts", twitter_accounts_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
	   <%= link_to "Tweets", tweets_path, class:"nav-link" %>
      </li>


      <li class="nav-item">
	   <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>
      <li class="nav-item">
	   <%= link_to "Edit Profile", edit_user_registration_path,class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
	   <%= link_to "Sign Up", new_user_registration_path ,class:"nav-link" %>
      </li>
      <li class="nav-item">
	   <%= link_to "Sign In", new_user_session_path ,class:"nav-link" %>
      </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittertest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">  
  </head>

  <body>
	  <%= render 'layouts/header'%>
      <% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %> <% if alert %> <p class="alert alert-danger"><%= alert %></p> <% end %>
      <div class="container">
      <%= yield %>
      </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
	<div class="alert alert-danger">
		<% form.object.errors.full_messages.each do |message| %>
			<div><%= message%></div>
		<% end %>
	</div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
        <%= render "shared/form_errors", form: form %>
        <div class="mb-3">
        <%= form.label :twitter_account_id %>
        <%= form.collection_select :twitter_account_id, current_user.twitter_accounts, :id, :username, {}, {class:"form-control"}%>
        <%= link_to "Connect your Twitter Account", "/auth/twitter", method: :post%>
        </div>
<div class="mb-3">
                <%= form.label :body %>
                <%= form.text_area :body, class: "form-control"%>
        </div>
<div class="mb-3">
                <%= form.label :publish_at %>
                <div class="form-control">
                        <%= form.datetime_select :publish_at %>
                </div>
        </div>
<%= form.button "Schedule", class: "btn btn-primary" %>


<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
	<%= tweet.body %>
	<div class="me-4">
	<%= image_tag tweet.twitter_account.image, class: "rounded-circle"%>
	<%= link_to "@#{tweet.twitter_account.username}","https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>

	<% if tweet.published? %>
		<%= link_to "View Tweet","https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
	<% else %>
		Scheduled for <%= l tweet.publish_at, format: :long %>
		<%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
	<% end %>

	</div>

</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render "form", tweet: @tweet %>

<% if @tweet.persisted? %>
	<%= button_to "Delete", @tweet, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-outline-danger mt-3" %>
<% end %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
	<h1>Tweets</h1>
	<% if current_user.twitter_accounts.any? %>
		<%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary"%>
	<% end %>

</div>
	<% if current_user.twitter_accounts.none? %>
		<%= link_to "Connect your Twitter Account", "/auth/twitter", class: "btn btn-primary"%>
	<% end %>

	<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
	<h1>Twitter Accounts</h1>
	<%= link_to "Connect a Twitter account", "/auth/twitter", method: :post, class: "btn btn-primary"%>
</div>

<% @twitter_accounts.each do |twitter_account| %>
	<div class="d-flex align-items-center mb-4">
		<div class="me-4">
			<%= image_tag twitter_account.image, class: "rounded-circle"%>
			<%= link_to "@#{twitter_account.username}","https://twitter.com/#{twitter_account.username}", target: :_blank %>
		</div>
	<%= button_to "Disconnect", twitter_account, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary" %>
	</div>
<% end %>